name: "publish"

on: 
   push: 
     branches: [ main ]
   pull_request:
     branches: [ main ]


jobs: 
  publish:
     name: publishing
     runs-on: ubuntu-latest

     steps:
        - name: checkout 
          uses: actions/checkout@v3.0.2
        - name: installation of node 
          uses: actions/setup-node@v3
          with: 
            node-version: 14
            registry-url: 'https://registry.npmjs.org/'
       # - name: configure
         # run: npm config set registry https://registry.npmjs.org/npm-modue-test  
        - name: publish
          run: npm install
          run: npm publish #--access public
          env:
            token: ${{ secrets.NPM_AUTH_TOKEN }} 
        